// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(MContext))]
    [Migration("20251204202845_ApplyNewModels")]
    partial class ApplyNewModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.Cycle", b =>
                {
                    b.Property<int>("IdSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idseq");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSeq"));

                    b.Property<int>("MachineConfIdSeq")
                        .HasColumnType("integer")
                        .HasColumnName("machineconfidseq");

                    b.Property<int>("ProductionOrderIdSeq")
                        .HasColumnType("integer")
                        .HasColumnName("productionorderidseq");

                    b.Property<int>("finished")
                        .HasColumnType("integer")
                        .HasColumnName("finished");

                    b.Property<int>("parts_per_cycle")
                        .HasColumnType("integer")
                        .HasColumnName("parts_per_cycle");

                    b.HasKey("IdSeq")
                        .HasName("pk_cycles");

                    b.HasIndex("MachineConfIdSeq")
                        .HasDatabaseName("ix_cycles_machineconfidseq");

                    b.HasIndex("ProductionOrderIdSeq")
                        .HasDatabaseName("ix_cycles_productionorderidseq");

                    b.ToTable("cycles");
                });

            modelBuilder.Entity("Core.Entities.Machine", b =>
                {
                    b.Property<int>("IdSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idseq");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSeq"));

                    b.Property<string>("Name_machine")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name_machine");

                    b.Property<string>("area")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("area");

                    b.HasKey("IdSeq")
                        .HasName("pk_machines");

                    b.ToTable("machines");
                });

            modelBuilder.Entity("Core.Entities.Machine_config", b =>
                {
                    b.Property<int>("IdSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idseq");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSeq"));

                    b.Property<int>("MachinesIdSeq")
                        .HasColumnType("integer")
                        .HasColumnName("machinesidseq");

                    b.Property<decimal>("cycle_duration")
                        .HasColumnType("numeric")
                        .HasColumnName("cycle_duration");

                    b.Property<int>("grit")
                        .HasColumnType("integer")
                        .HasColumnName("grit");

                    b.Property<string>("operator_name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("operator_name");

                    b.Property<decimal>("pressure")
                        .HasColumnType("numeric")
                        .HasColumnName("pressure");

                    b.HasKey("IdSeq")
                        .HasName("pk_machineconfigs");

                    b.HasIndex("MachinesIdSeq")
                        .HasDatabaseName("ix_machineconfigs_machinesidseq");

                    b.ToTable("machineconfigs");
                });

            modelBuilder.Entity("Core.Entities.Part", b =>
                {
                    b.Property<int>("IdSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idseq");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSeq"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("material");

                    b.Property<string>("PartNum")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("partnum")
                        .HasComputedColumnSql("'PN-' || lpad(\"IdSeq\"::text, 6, '0')", true);

                    b.Property<string>("Sequence")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("sequence");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("weight");

                    b.HasKey("IdSeq")
                        .HasName("pk_parts");

                    b.ToTable("parts");
                });

            modelBuilder.Entity("Core.Entities.Production_order", b =>
                {
                    b.Property<int>("IdSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idseq");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSeq"));

                    b.Property<int>("PartIdSeq")
                        .HasColumnType("integer")
                        .HasColumnName("partidseq");

                    b.Property<int>("final_quantity")
                        .HasColumnType("integer")
                        .HasColumnName("final_quantity");

                    b.Property<DateTime?>("finished_time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_time");

                    b.Property<DateTime>("started_time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_time");

                    b.Property<int>("target_quantity")
                        .HasColumnType("integer")
                        .HasColumnName("target_quantity");

                    b.HasKey("IdSeq")
                        .HasName("pk_production_orders");

                    b.HasIndex("PartIdSeq")
                        .HasDatabaseName("ix_production_orders_partidseq");

                    b.ToTable("production_orders");
                });

            modelBuilder.Entity("Core.Entities.Cycle", b =>
                {
                    b.HasOne("Core.Entities.Machine_config", "MachineConfig")
                        .WithMany("Cycle")
                        .HasForeignKey("MachineConfIdSeq")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cycles_machineconfigs_machineconfidseq");

                    b.HasOne("Core.Entities.Production_order", "ProductionOrder")
                        .WithMany("Cycle")
                        .HasForeignKey("ProductionOrderIdSeq")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cycles_production_orders_productionorderidseq");

                    b.Navigation("MachineConfig");

                    b.Navigation("ProductionOrder");
                });

            modelBuilder.Entity("Core.Entities.Machine_config", b =>
                {
                    b.HasOne("Core.Entities.Machine", "Machine")
                        .WithMany("MachineConfigs")
                        .HasForeignKey("MachinesIdSeq")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_machineconfigs_machines_machinesidseq");

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("Core.Entities.Production_order", b =>
                {
                    b.HasOne("Core.Entities.Part", "Part")
                        .WithMany("Productionorder")
                        .HasForeignKey("PartIdSeq")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_production_orders_parts_partidseq");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("Core.Entities.Machine", b =>
                {
                    b.Navigation("MachineConfigs");
                });

            modelBuilder.Entity("Core.Entities.Machine_config", b =>
                {
                    b.Navigation("Cycle");
                });

            modelBuilder.Entity("Core.Entities.Part", b =>
                {
                    b.Navigation("Productionorder");
                });

            modelBuilder.Entity("Core.Entities.Production_order", b =>
                {
                    b.Navigation("Cycle");
                });
#pragma warning restore 612, 618
        }
    }
}
